### ISSUE TITLE
The password of the paper.zip

### ISSUE THREAD

**Issue by xwc940512** [lmassaron/recsys_summer_school_2017#1]
HI:
  I appreciate your help very much. Could I have the password of the paper.zip?

**Comment by lmassaron** [comment]
Sorry, it is a reserved file containing materials that were shared to participants only to the RecSYS Summer School 2017. You can find all the original documents at http://pro.unibz.it/projects/schoolrecsys17/program.html what you can get from my repositories are the files that I personally elaborated, stored and shared.
